apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-service
  labels:
    app: gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gate
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - name: gate
        image: trin9/gate-service:latest # ⚠️ change this
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: VLLM_URL
          value: "http://vllm-qwen-service.default.svc.cluster.local:8000/v1/chat/completions"
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gate-service-entry
spec:
  selector:
    app: gate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP   # use a tunnel locally; AWS creates an ELB automatically