apiVersion: v2
name: monitoring-stack
description: A Helm chart for deploying kube-prometheus-stack and LLM serving dashboards
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: kube-prometheus-stack
  version: "89.2.2"
  repository: "https://prometheus-community.github.io/helm-charts"
