# Configure Prometheus
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  server:
    global:
      scrape_interval: 30s
      scrape_timeout: 20s
      evaluation_interval: 30s
# Configure Grafana
grafana:
  adminPassword: "admin"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: "default"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://monitoring-stack-prometheus-server.default.svc.cluster.local
        access: proxy
        isDefault: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi